"""Pydantic schemas for FastAPI-native material purchase orders."""

from __future__ import annotations

from datetime import date
from datetime import datetime
from decimal import Decimal
from typing import Literal

from pydantic import AliasChoices
from pydantic import BaseModel
from pydantic import Field

PurchaseOrderStatus = Literal["draft", "partially_received", "received", "cancelled"]
PurchaseRequirementStatus = Literal["pending", "purchased", "completed", "cancelled"]
PurchaseInvoiceStatus = Literal["submitted", "partly_paid", "paid", "cancelled"]
PurchasePaymentStatus = Literal["pending_approval", "submitted", "cancelled"]


class MaterialPurchaseOrderLineCreate(BaseModel):
    """Create payload line."""

    item_code: str | None = Field(default=None, max_length=140)
    material_item_code: str = Field(..., min_length=1, max_length=140)
    material_name: str = Field(default="", max_length=255)
    qty: Decimal = Field(..., gt=0)
    uom: str = Field(default="米", min_length=1, max_length=32)
    unit_price: Decimal = Field(default=0, ge=0)
    warehouse: str | None = Field(default=None, max_length=140)


class MaterialPurchaseOrderCreateRequest(BaseModel):
    """Create purchase order request."""

    operation: Literal["create"] = "create"
    company: str = Field(default="默认公司", min_length=1, max_length=140)
    purchase_no: str | None = Field(default=None, max_length=140)
    supplier_name: str = Field(..., min_length=1, max_length=255)
    transaction_date: date | None = None
    expected_delivery_date: date | None = None
    currency: str = Field(default="CNY", min_length=1, max_length=32)
    idempotency_key: str = Field(..., min_length=1, max_length=140)
    items: list[MaterialPurchaseOrderLineCreate] = Field(min_length=1)


class MaterialPurchaseOrderListItem(BaseModel):
    """Purchase order row returned to existing frontend table."""

    id: int
    order_id: int
    line_id: int
    company: str
    purchase_no: str
    supplier_name: str
    item_code: str
    material_item_code: str
    material_name: str
    qty: Decimal
    received_qty: Decimal
    uom: str
    unit_price: Decimal
    total_amount: Decimal
    expected_delivery_date: date | None = None
    transaction_date: date | None = None
    status: PurchaseOrderStatus
    warehouse: str | None = None
    currency: str = "CNY"
    created_at: datetime | None = None


class MaterialPurchaseOrderData(BaseModel):
    """Paginated purchase order rows."""

    items: list[MaterialPurchaseOrderListItem]
    total: int
    page: int
    page_size: int


class MaterialPurchaseOrderCreateData(BaseModel):
    """Create response."""

    id: int
    purchase_no: str
    company: str
    supplier_name: str
    status: PurchaseOrderStatus
    total_qty: Decimal
    received_qty: Decimal
    total_amount: Decimal
    currency: str
    idempotency_key: str
    created_at: datetime | None = None
    items: list[MaterialPurchaseOrderListItem]


class MaterialPurchaseOrderCancelRequest(BaseModel):
    """Cancel purchase order and release linked requirement pool rows."""

    operation: Literal["cancel_order"] = "cancel_order"
    company: str = Field(default="默认公司", min_length=1, max_length=140)
    reason: str = Field(default="前端物料采购单取消", min_length=1, max_length=255)
    idempotency_key: str = Field(..., min_length=1, max_length=140)


class MaterialPurchaseRequirementListItem(BaseModel):
    """Material requirement pool row generated by material check."""

    id: int
    company: str
    requirement_no: str
    source_type: str
    source_id: str
    source_no: str | None = None
    plan_id: int | None = None
    bom_item_id: int | None = None
    sales_order: str | None = None
    sales_order_item: str | None = None
    item_code: str | None = None
    material_item_code: str
    material_name: str
    supplier_name: str | None = None
    warehouse: str
    required_qty: Decimal
    available_qty: Decimal
    net_required_qty: Decimal
    purchased_qty: Decimal
    received_qty: Decimal
    uom: str
    unit_price: Decimal
    status: PurchaseRequirementStatus
    has_completed: bool
    purchase_no: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None


class MaterialPurchaseRequirementListData(BaseModel):
    """Paginated material requirement pool."""

    items: list[MaterialPurchaseRequirementListItem]
    total: int
    page: int
    page_size: int


class MaterialPurchaseRequirementToOrderRequest(BaseModel):
    """Create one purchase order from selected requirement pool rows."""

    operation: Literal["create_order_from_requirements"] = "create_order_from_requirements"
    company: str = Field(default="默认公司", min_length=1, max_length=140)
    requirement_ids: list[int] = Field(min_length=1)
    supplier_name: str | None = Field(default=None, max_length=255)
    purchase_no: str | None = Field(default=None, max_length=140)
    transaction_date: date | None = None
    expected_delivery_date: date | None = None
    currency: str = Field(default="CNY", min_length=1, max_length=32)
    idempotency_key: str = Field(..., min_length=1, max_length=140)
    group_by_material: bool = Field(default=True, validation_alias=AliasChoices("group_by_material", "groupByMaterial"))


class MaterialPurchaseRequirementToOrderData(BaseModel):
    """Create purchase order from requirements response."""

    purchase_order: MaterialPurchaseOrderCreateData
    requirements: list[MaterialPurchaseRequirementListItem]


class MaterialPurchaseOrderCancelData(BaseModel):
    """Cancel purchase order response."""

    purchase_order: MaterialPurchaseOrderCreateData
    requirements: list[MaterialPurchaseRequirementListItem]
    reason: str


class MaterialPurchaseInvoiceCreateRequest(BaseModel):
    """Create purchase invoice and payable request."""

    operation: Literal["create_purchase_invoice"] = "create_purchase_invoice"
    company: str = Field(default="默认公司", min_length=1, max_length=140)
    purchase_no: str = Field(..., min_length=1, max_length=140)
    supplier_name: str | None = Field(default=None, max_length=255)
    material_item_code: str | None = Field(default=None, max_length=140)
    qty: Decimal | None = Field(default=None, gt=0)
    rate: Decimal | None = Field(default=None, ge=0)
    posting_date: date
    due_date: date | None = None
    purchase_invoice: str | None = Field(default=None, max_length=140)
    source_ref: str | None = Field(default=None, max_length=140)
    idempotency_key: str = Field(..., min_length=1, max_length=140)
    scenario_tag: str | None = Field(default=None, max_length=64)


class MaterialPurchaseInvoiceData(BaseModel):
    """Purchase invoice/payable row."""

    id: int
    company: str
    purchase_invoice: str
    purchase_order_id: int
    purchase_no: str
    supplier_name: str
    material_item_code: str
    material_name: str
    warehouse: str | None = None
    qty: Decimal
    uom: str
    rate: Decimal
    grand_total: Decimal
    paid_amount: Decimal
    outstanding_amount: Decimal
    posting_date: date
    due_date: date | None = None
    status: PurchaseInvoiceStatus
    docstatus: int
    source_ref: str
    idempotency_key: str
    scenario_tag: str | None = None
    approval_status: str = "not_submitted"
    approval_no: str | None = None
    financial_ledger_status: str = "posted"
    financial_ledger_status_name: str = "总账已归集"
    financial_ledger_payable_amount: Decimal = Decimal("0")
    financial_ledger_cash_out_amount: Decimal = Decimal("0")
    financial_ledger_outstanding_amount: Decimal = Decimal("0")
    financial_ledger_closed: bool = False
    financial_ledger_source_note: str = ""
    created_by: str
    created_at: datetime | None = None


class MaterialPurchaseInvoiceListData(BaseModel):
    """Paginated purchase invoice rows."""

    items: list[MaterialPurchaseInvoiceData]
    total: int
    page: int
    page_size: int


class MaterialPurchasePaymentCreateRequest(BaseModel):
    """Create supplier payment entry request."""

    operation: Literal["create_purchase_payment"] = "create_purchase_payment"
    company: str = Field(default="默认公司", min_length=1, max_length=140)
    purchase_invoice: str = Field(..., min_length=1, max_length=140)
    supplier_name: str | None = Field(default=None, max_length=255)
    posting_date: date
    paid_amount: Decimal = Field(..., gt=0)
    mode_of_payment: str = Field(default="Bank Transfer", min_length=1, max_length=140)
    reference_no: str | None = Field(default=None, max_length=140)
    reference_date: date | None = None
    payment_entry: str | None = Field(default=None, max_length=140)
    source_ref: str | None = Field(default=None, max_length=140)
    idempotency_key: str = Field(..., min_length=1, max_length=140)
    scenario_tag: str | None = Field(default=None, max_length=64)


class MaterialPurchasePaymentCancelRequest(BaseModel):
    """Cancel supplier payment entry request."""

    operation: Literal["cancel_purchase_payment"] = "cancel_purchase_payment"
    company: str = Field(default="默认公司", min_length=1, max_length=140)
    purchase_invoice: str = Field(..., min_length=1, max_length=140)
    reason: str | None = Field(default=None, max_length=500)
    idempotency_key: str = Field(..., min_length=1, max_length=140)
    scenario_tag: str | None = Field(default=None, max_length=64)


class MaterialPurchasePaymentData(BaseModel):
    """Supplier payment entry row."""

    id: int
    company: str
    payment_entry: str
    purchase_invoice_id: int
    purchase_invoice: str
    purchase_no: str
    supplier_name: str
    posting_date: date
    paid_amount: Decimal
    allocated_amount: Decimal
    outstanding_before: Decimal
    outstanding_after: Decimal
    mode_of_payment: str
    reference_no: str | None = None
    reference_date: date | None = None
    status: PurchasePaymentStatus
    docstatus: int
    source_ref: str
    idempotency_key: str
    scenario_tag: str | None = None
    approval_status: str = "not_submitted"
    approval_no: str | None = None
    financial_ledger_status: str = "pending"
    financial_ledger_status_name: str = "待审批"
    financial_ledger_cash_out_amount: Decimal = Decimal("0")
    financial_ledger_outstanding_amount: Decimal = Decimal("0")
    financial_ledger_closed: bool = False
    financial_ledger_source_note: str = ""
    created_by: str
    created_at: datetime | None = None


class MaterialPurchasePaymentListData(BaseModel):
    """Paginated supplier payment entries."""

    items: list[MaterialPurchasePaymentData]
    total: int
    page: int
    page_size: int
