"""Application error code constants and metadata."""

from __future__ import annotations

BOM_NOT_FOUND = "BOM_NOT_FOUND"
BOM_ITEM_NOT_FOUND = "BOM_ITEM_NOT_FOUND"
BOM_INVALID_QTY = "BOM_INVALID_QTY"
BOM_INVALID_LOSS_RATE = "BOM_INVALID_LOSS_RATE"
BOM_OPERATION_RATE_REQUIRED = "BOM_OPERATION_RATE_REQUIRED"
BOM_PUBLISHED_LOCKED = "BOM_PUBLISHED_LOCKED"
BOM_DEFAULT_REQUIRES_ACTIVE = "BOM_DEFAULT_REQUIRES_ACTIVE"
BOM_DEFAULT_CONFLICT = "BOM_DEFAULT_CONFLICT"
BOM_STATUS_INVALID = "BOM_STATUS_INVALID"
BOM_INTERNAL_ERROR = "BOM_INTERNAL_ERROR"

SUBCONTRACT_NOT_FOUND = "SUBCONTRACT_NOT_FOUND"
SUBCONTRACT_STATUS_INVALID = "SUBCONTRACT_STATUS_INVALID"
SUBCONTRACT_SUPPLIER_INVALID = "SUBCONTRACT_SUPPLIER_INVALID"
SUBCONTRACT_ITEM_NOT_FOUND = "SUBCONTRACT_ITEM_NOT_FOUND"
SUBCONTRACT_PROCESS_NOT_SUBCONTRACT = "SUBCONTRACT_PROCESS_NOT_SUBCONTRACT"
SUBCONTRACT_BOM_ITEM_MISMATCH = "SUBCONTRACT_BOM_ITEM_MISMATCH"
SUBCONTRACT_WAREHOUSE_INVALID = "SUBCONTRACT_WAREHOUSE_INVALID"
SUBCONTRACT_INVALID_QTY = "SUBCONTRACT_INVALID_QTY"
SUBCONTRACT_RATE_REQUIRED = "SUBCONTRACT_RATE_REQUIRED"
SUBCONTRACT_IDEMPOTENCY_CONFLICT = "SUBCONTRACT_IDEMPOTENCY_CONFLICT"
SUBCONTRACT_SETTLEMENT_LOCKED = "SUBCONTRACT_SETTLEMENT_LOCKED"
SUBCONTRACT_SETTLEMENT_CANDIDATE_NOT_FOUND = "SUBCONTRACT_SETTLEMENT_CANDIDATE_NOT_FOUND"
SUBCONTRACT_SETTLEMENT_ALREADY_LOCKED = "SUBCONTRACT_SETTLEMENT_ALREADY_LOCKED"
SUBCONTRACT_SETTLEMENT_STATUS_INVALID = "SUBCONTRACT_SETTLEMENT_STATUS_INVALID"
SUBCONTRACT_SETTLEMENT_IDEMPOTENCY_CONFLICT = "SUBCONTRACT_SETTLEMENT_IDEMPOTENCY_CONFLICT"
SUBCONTRACT_SETTLEMENT_STATEMENT_REQUIRED = "SUBCONTRACT_SETTLEMENT_STATEMENT_REQUIRED"
SUBCONTRACT_STOCK_SYNC_FAILED = "SUBCONTRACT_STOCK_SYNC_FAILED"
SUBCONTRACT_STOCK_OUTBOX_REQUIRED = "SUBCONTRACT_STOCK_OUTBOX_REQUIRED"
SUBCONTRACT_STOCK_OUTBOX_NOT_FOUND = "SUBCONTRACT_STOCK_OUTBOX_NOT_FOUND"
SUBCONTRACT_STOCK_OUTBOX_CONFLICT = "SUBCONTRACT_STOCK_OUTBOX_CONFLICT"
SUBCONTRACT_STOCK_OUTBOX_ORDER_MISMATCH = "SUBCONTRACT_STOCK_OUTBOX_ORDER_MISMATCH"
SUBCONTRACT_STOCK_OUTBOX_ACTION_MISMATCH = "SUBCONTRACT_STOCK_OUTBOX_ACTION_MISMATCH"
SUBCONTRACT_STOCK_OUTBOX_IDEMPOTENCY_MISMATCH = "SUBCONTRACT_STOCK_OUTBOX_IDEMPOTENCY_MISMATCH"
SUBCONTRACT_STOCK_OUTBOX_NOT_RETRYABLE = "SUBCONTRACT_STOCK_OUTBOX_NOT_RETRYABLE"
SUBCONTRACT_STOCK_OUTBOX_SCOPE_FORBIDDEN = "SUBCONTRACT_STOCK_OUTBOX_SCOPE_FORBIDDEN"
SUBCONTRACT_COMPANY_REQUIRED = "SUBCONTRACT_COMPANY_REQUIRED"
SUBCONTRACT_COMPANY_UNRESOLVED = "SUBCONTRACT_COMPANY_UNRESOLVED"
SUBCONTRACT_COMPANY_AMBIGUOUS = "SUBCONTRACT_COMPANY_AMBIGUOUS"
SUBCONTRACT_SCOPE_BLOCKED = "SUBCONTRACT_SCOPE_BLOCKED"
SUBCONTRACT_MATERIAL_NOT_IN_BOM = "SUBCONTRACT_MATERIAL_NOT_IN_BOM"
SUBCONTRACT_MATERIAL_QTY_EXCEEDED = "SUBCONTRACT_MATERIAL_QTY_EXCEEDED"
SUBCONTRACT_RECEIPT_WAREHOUSE_REQUIRED = "SUBCONTRACT_RECEIPT_WAREHOUSE_REQUIRED"
SUBCONTRACT_RECEIPT_BATCH_REQUIRED = "SUBCONTRACT_RECEIPT_BATCH_REQUIRED"
SUBCONTRACT_RECEIPT_BATCH_NOT_FOUND = "SUBCONTRACT_RECEIPT_BATCH_NOT_FOUND"
SUBCONTRACT_RECEIPT_NOT_SYNCED = "SUBCONTRACT_RECEIPT_NOT_SYNCED"
SUBCONTRACT_RECEIPT_QTY_EXCEEDED = "SUBCONTRACT_RECEIPT_QTY_EXCEEDED"
SUBCONTRACT_RECEIPT_ITEM_INVALID = "SUBCONTRACT_RECEIPT_ITEM_INVALID"
SUBCONTRACT_INSPECTION_NOT_READY = "SUBCONTRACT_INSPECTION_NOT_READY"
SUBCONTRACT_INSPECTION_QTY_EXCEEDED = "SUBCONTRACT_INSPECTION_QTY_EXCEEDED"
SUBCONTRACT_REJECTED_QTY_EXCEEDS_INSPECTED = "SUBCONTRACT_REJECTED_QTY_EXCEEDS_INSPECTED"
SUBCONTRACT_DEDUCTION_EXCEEDS_GROSS = "SUBCONTRACT_DEDUCTION_EXCEEDS_GROSS"
SUBCONTRACT_MIGRATION_DRY_RUN_ONLY = "SUBCONTRACT_MIGRATION_DRY_RUN_ONLY"
SUBCONTRACT_OUTBOX_REQUIRED = "SUBCONTRACT_OUTBOX_REQUIRED"
SUBCONTRACT_INSPECTION_NOT_IMPLEMENTED = "SUBCONTRACT_INSPECTION_NOT_IMPLEMENTED"
SUBCONTRACT_WAREHOUSE_REQUIRED = "SUBCONTRACT_WAREHOUSE_REQUIRED"
SUBCONTRACT_DRY_RUN_DISABLED = "SUBCONTRACT_DRY_RUN_DISABLED"
SUBCONTRACT_WORKER_DISABLED = "SUBCONTRACT_WORKER_DISABLED"
SUBCONTRACT_INTERNAL_ERROR = "SUBCONTRACT_INTERNAL_ERROR"

PRODUCTION_SO_NOT_FOUND = "PRODUCTION_SO_NOT_FOUND"
PRODUCTION_SO_NOT_APPROVED = "PRODUCTION_SO_NOT_APPROVED"
PRODUCTION_SO_CLOSED_OR_CANCELLED = "PRODUCTION_SO_CLOSED_OR_CANCELLED"
PRODUCTION_SO_ITEM_NOT_FOUND = "PRODUCTION_SO_ITEM_NOT_FOUND"
PRODUCTION_SO_ITEM_AMBIGUOUS = "PRODUCTION_SO_ITEM_AMBIGUOUS"
PRODUCTION_BOM_NOT_FOUND = "PRODUCTION_BOM_NOT_FOUND"
PRODUCTION_BOM_NOT_ACTIVE = "PRODUCTION_BOM_NOT_ACTIVE"
PRODUCTION_BOM_ITEM_MISMATCH = "PRODUCTION_BOM_ITEM_MISMATCH"
PRODUCTION_PLANNED_QTY_EXCEEDED = "PRODUCTION_PLANNED_QTY_EXCEEDED"
PRODUCTION_IDEMPOTENCY_CONFLICT = "PRODUCTION_IDEMPOTENCY_CONFLICT"
PRODUCTION_WAREHOUSE_REQUIRED = "PRODUCTION_WAREHOUSE_REQUIRED"
PRODUCTION_START_DATE_REQUIRED = "PRODUCTION_START_DATE_REQUIRED"
PRODUCTION_IDEMPOTENCY_KEY_REQUIRED = "PRODUCTION_IDEMPOTENCY_KEY_REQUIRED"
PRODUCTION_WORK_ORDER_ALREADY_EXISTS = "PRODUCTION_WORK_ORDER_ALREADY_EXISTS"
PRODUCTION_WORK_ORDER_SYNC_FAILED = "PRODUCTION_WORK_ORDER_SYNC_FAILED"
PRODUCTION_JOB_CARD_SYNC_FAILED = "PRODUCTION_JOB_CARD_SYNC_FAILED"
PRODUCTION_INTERNAL_ERROR = "PRODUCTION_INTERNAL_ERROR"

STYLE_PROFIT_NOT_FOUND = "STYLE_PROFIT_NOT_FOUND"
STYLE_PROFIT_CLIENT_SOURCE_FORBIDDEN = "STYLE_PROFIT_CLIENT_SOURCE_FORBIDDEN"
STYLE_PROFIT_INVALID_PERIOD = "STYLE_PROFIT_INVALID_PERIOD"
STYLE_PROFIT_INVALID_REVENUE_MODE = "STYLE_PROFIT_INVALID_REVENUE_MODE"
STYLE_PROFIT_INVALID_FORMULA_VERSION = "STYLE_PROFIT_INVALID_FORMULA_VERSION"
STYLE_PROFIT_INVALID_IDEMPOTENCY_KEY = "STYLE_PROFIT_INVALID_IDEMPOTENCY_KEY"
STYLE_PROFIT_SALES_ORDER_REQUIRED = "STYLE_PROFIT_SALES_ORDER_REQUIRED"
STYLE_PROFIT_BOM_REQUIRED = "STYLE_PROFIT_BOM_REQUIRED"
STYLE_PROFIT_REVENUE_SOURCE_REQUIRED = "STYLE_PROFIT_REVENUE_SOURCE_REQUIRED"
STYLE_PROFIT_IDEMPOTENCY_CONFLICT = "STYLE_PROFIT_IDEMPOTENCY_CONFLICT"
STYLE_PROFIT_SOURCE_UNAVAILABLE = "STYLE_PROFIT_SOURCE_UNAVAILABLE"
STYLE_PROFIT_SOURCE_READ_FAILED = "STYLE_PROFIT_SOURCE_READ_FAILED"
STYLE_PROFIT_INTERNAL_ERROR = "STYLE_PROFIT_INTERNAL_ERROR"

WORKSHOP_TICKET_NOT_FOUND = "WORKSHOP_TICKET_NOT_FOUND"
WORKSHOP_JOB_CARD_NOT_FOUND = "WORKSHOP_JOB_CARD_NOT_FOUND"
WORKSHOP_EMPLOYEE_NOT_FOUND = "WORKSHOP_EMPLOYEE_NOT_FOUND"
WORKSHOP_JOB_CARD_STATUS_INVALID = "WORKSHOP_JOB_CARD_STATUS_INVALID"
WORKSHOP_PROCESS_MISMATCH = "WORKSHOP_PROCESS_MISMATCH"
WORKSHOP_ITEM_MISMATCH = "WORKSHOP_ITEM_MISMATCH"
WORKSHOP_JOB_CARD_ITEM_NOT_FOUND = "WORKSHOP_JOB_CARD_ITEM_NOT_FOUND"
WORKSHOP_JOB_CARD_COMPANY_NOT_FOUND = "WORKSHOP_JOB_CARD_COMPANY_NOT_FOUND"
WORKSHOP_INVALID_QTY = "WORKSHOP_INVALID_QTY"
WORKSHOP_IDEMPOTENCY_CONFLICT = "WORKSHOP_IDEMPOTENCY_CONFLICT"
WORKSHOP_REVERSAL_EXCEEDS_REGISTERED = "WORKSHOP_REVERSAL_EXCEEDS_REGISTERED"
WORKSHOP_WAGE_RATE_NOT_FOUND = "WORKSHOP_WAGE_RATE_NOT_FOUND"
WORKSHOP_WAGE_RATE_OVERLAP = "WORKSHOP_WAGE_RATE_OVERLAP"
WORKSHOP_WAGE_RATE_COMPANY_REQUIRED = "WORKSHOP_WAGE_RATE_COMPANY_REQUIRED"
WORKSHOP_WAGE_RATE_SCOPE_REQUIRED = "WORKSHOP_WAGE_RATE_SCOPE_REQUIRED"
WORKSHOP_WAGE_RATE_COMPANY_AMBIGUOUS = "WORKSHOP_WAGE_RATE_COMPANY_AMBIGUOUS"
WORKSHOP_WAGE_RATE_COMPANY_UNRESOLVED = "WORKSHOP_WAGE_RATE_COMPANY_UNRESOLVED"
WORKSHOP_WAGE_RATE_GLOBAL_FORBIDDEN = "WORKSHOP_WAGE_RATE_GLOBAL_FORBIDDEN"
WORKSHOP_JOB_CARD_SYNC_FAILED = "WORKSHOP_JOB_CARD_SYNC_FAILED"
WORKSHOP_OUTBOX_NOT_FOUND = "WORKSHOP_OUTBOX_NOT_FOUND"
WORKSHOP_OUTBOX_ALREADY_SUCCEEDED = "WORKSHOP_OUTBOX_ALREADY_SUCCEEDED"
WORKSHOP_OUTBOX_LOCKED = "WORKSHOP_OUTBOX_LOCKED"
WORKSHOP_JOB_CARD_SYNC_PENDING = "WORKSHOP_JOB_CARD_SYNC_PENDING"
WORKSHOP_INTERNAL_ERROR = "WORKSHOP_INTERNAL_ERROR"
WORKSHOP_DRY_RUN_DISABLED = "WORKSHOP_DRY_RUN_DISABLED"

AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
PERMISSION_SOURCE_UNAVAILABLE = "PERMISSION_SOURCE_UNAVAILABLE"
ERPNEXT_SERVICE_UNAVAILABLE = "ERPNEXT_SERVICE_UNAVAILABLE"
ERPNEXT_SERVICE_ACCOUNT_FORBIDDEN = "ERPNEXT_SERVICE_ACCOUNT_FORBIDDEN"
ERPNEXT_CUSTOM_FIELD_MISSING = "ERPNEXT_CUSTOM_FIELD_MISSING"
ERPNEXT_STOCK_ENTRY_CREATE_FAILED = "ERPNEXT_STOCK_ENTRY_CREATE_FAILED"
ERPNEXT_STOCK_ENTRY_SUBMIT_FAILED = "ERPNEXT_STOCK_ENTRY_SUBMIT_FAILED"
ERPNEXT_STOCK_ENTRY_CANCELLED = "ERPNEXT_STOCK_ENTRY_CANCELLED"
ERPNEXT_STOCK_ENTRY_STATUS_INVALID = "ERPNEXT_STOCK_ENTRY_STATUS_INVALID"
ERPNEXT_STOCK_ENTRY_DUPLICATE_EVENT_KEY = "ERPNEXT_STOCK_ENTRY_DUPLICATE_EVENT_KEY"
INTERNAL_API_DISABLED = "INTERNAL_API_DISABLED"
SERVICE_ACCOUNT_RESOURCE_FORBIDDEN = "SERVICE_ACCOUNT_RESOURCE_FORBIDDEN"
SERVICE_ACCOUNT_RESOURCE_SCOPE_REQUIRED = "SERVICE_ACCOUNT_RESOURCE_SCOPE_REQUIRED"

AUDIT_WRITE_FAILED = "AUDIT_WRITE_FAILED"
DATABASE_WRITE_FAILED = "DATABASE_WRITE_FAILED"
DATABASE_READ_FAILED = "DATABASE_READ_FAILED"

HTTP_STATUS_BY_CODE: dict[str, int] = {
    BOM_NOT_FOUND: 404,
    BOM_ITEM_NOT_FOUND: 400,
    BOM_INVALID_QTY: 400,
    BOM_INVALID_LOSS_RATE: 400,
    BOM_OPERATION_RATE_REQUIRED: 400,
    BOM_PUBLISHED_LOCKED: 409,
    BOM_DEFAULT_REQUIRES_ACTIVE: 400,
    BOM_DEFAULT_CONFLICT: 409,
    BOM_STATUS_INVALID: 409,
    SUBCONTRACT_NOT_FOUND: 404,
    SUBCONTRACT_STATUS_INVALID: 409,
    SUBCONTRACT_SUPPLIER_INVALID: 400,
    SUBCONTRACT_ITEM_NOT_FOUND: 400,
    SUBCONTRACT_PROCESS_NOT_SUBCONTRACT: 400,
    SUBCONTRACT_BOM_ITEM_MISMATCH: 400,
    SUBCONTRACT_WAREHOUSE_INVALID: 400,
    SUBCONTRACT_INVALID_QTY: 400,
    SUBCONTRACT_RATE_REQUIRED: 400,
    SUBCONTRACT_IDEMPOTENCY_CONFLICT: 409,
    SUBCONTRACT_SETTLEMENT_LOCKED: 409,
    SUBCONTRACT_SETTLEMENT_CANDIDATE_NOT_FOUND: 404,
    SUBCONTRACT_SETTLEMENT_ALREADY_LOCKED: 409,
    SUBCONTRACT_SETTLEMENT_STATUS_INVALID: 409,
    SUBCONTRACT_SETTLEMENT_IDEMPOTENCY_CONFLICT: 409,
    SUBCONTRACT_SETTLEMENT_STATEMENT_REQUIRED: 400,
    SUBCONTRACT_STOCK_SYNC_FAILED: 502,
    SUBCONTRACT_STOCK_OUTBOX_REQUIRED: 409,
    SUBCONTRACT_STOCK_OUTBOX_NOT_FOUND: 404,
    SUBCONTRACT_STOCK_OUTBOX_CONFLICT: 409,
    SUBCONTRACT_STOCK_OUTBOX_ORDER_MISMATCH: 409,
    SUBCONTRACT_STOCK_OUTBOX_ACTION_MISMATCH: 409,
    SUBCONTRACT_STOCK_OUTBOX_IDEMPOTENCY_MISMATCH: 409,
    SUBCONTRACT_STOCK_OUTBOX_NOT_RETRYABLE: 409,
    SUBCONTRACT_STOCK_OUTBOX_SCOPE_FORBIDDEN: 403,
    SUBCONTRACT_COMPANY_REQUIRED: 422,
    SUBCONTRACT_COMPANY_UNRESOLVED: 409,
    SUBCONTRACT_COMPANY_AMBIGUOUS: 409,
    SUBCONTRACT_SCOPE_BLOCKED: 409,
    SUBCONTRACT_MATERIAL_NOT_IN_BOM: 400,
    SUBCONTRACT_MATERIAL_QTY_EXCEEDED: 409,
    SUBCONTRACT_RECEIPT_WAREHOUSE_REQUIRED: 400,
    SUBCONTRACT_RECEIPT_BATCH_REQUIRED: 400,
    SUBCONTRACT_RECEIPT_BATCH_NOT_FOUND: 404,
    SUBCONTRACT_RECEIPT_NOT_SYNCED: 409,
    SUBCONTRACT_RECEIPT_QTY_EXCEEDED: 409,
    SUBCONTRACT_RECEIPT_ITEM_INVALID: 400,
    SUBCONTRACT_INSPECTION_NOT_READY: 409,
    SUBCONTRACT_INSPECTION_QTY_EXCEEDED: 409,
    SUBCONTRACT_REJECTED_QTY_EXCEEDS_INSPECTED: 409,
    SUBCONTRACT_DEDUCTION_EXCEEDS_GROSS: 409,
    SUBCONTRACT_MIGRATION_DRY_RUN_ONLY: 409,
    SUBCONTRACT_OUTBOX_REQUIRED: 409,
    SUBCONTRACT_INSPECTION_NOT_IMPLEMENTED: 409,
    SUBCONTRACT_WAREHOUSE_REQUIRED: 400,
    SUBCONTRACT_DRY_RUN_DISABLED: 403,
    SUBCONTRACT_WORKER_DISABLED: 403,
    SUBCONTRACT_INTERNAL_ERROR: 500,
    PRODUCTION_SO_NOT_FOUND: 404,
    PRODUCTION_SO_NOT_APPROVED: 409,
    PRODUCTION_SO_CLOSED_OR_CANCELLED: 409,
    PRODUCTION_SO_ITEM_NOT_FOUND: 404,
    PRODUCTION_SO_ITEM_AMBIGUOUS: 409,
    PRODUCTION_BOM_NOT_FOUND: 404,
    PRODUCTION_BOM_NOT_ACTIVE: 409,
    PRODUCTION_BOM_ITEM_MISMATCH: 409,
    PRODUCTION_PLANNED_QTY_EXCEEDED: 409,
    PRODUCTION_IDEMPOTENCY_CONFLICT: 409,
    PRODUCTION_WAREHOUSE_REQUIRED: 400,
    PRODUCTION_START_DATE_REQUIRED: 400,
    PRODUCTION_IDEMPOTENCY_KEY_REQUIRED: 400,
    PRODUCTION_WORK_ORDER_ALREADY_EXISTS: 409,
    PRODUCTION_WORK_ORDER_SYNC_FAILED: 502,
    PRODUCTION_JOB_CARD_SYNC_FAILED: 502,
    PRODUCTION_INTERNAL_ERROR: 500,
    STYLE_PROFIT_NOT_FOUND: 404,
    STYLE_PROFIT_CLIENT_SOURCE_FORBIDDEN: 400,
    STYLE_PROFIT_INVALID_PERIOD: 400,
    STYLE_PROFIT_INVALID_REVENUE_MODE: 400,
    STYLE_PROFIT_INVALID_FORMULA_VERSION: 400,
    STYLE_PROFIT_INVALID_IDEMPOTENCY_KEY: 400,
    STYLE_PROFIT_SALES_ORDER_REQUIRED: 400,
    STYLE_PROFIT_BOM_REQUIRED: 409,
    STYLE_PROFIT_REVENUE_SOURCE_REQUIRED: 409,
    STYLE_PROFIT_IDEMPOTENCY_CONFLICT: 409,
    STYLE_PROFIT_SOURCE_UNAVAILABLE: 503,
    STYLE_PROFIT_SOURCE_READ_FAILED: 400,
    STYLE_PROFIT_INTERNAL_ERROR: 500,
    WORKSHOP_TICKET_NOT_FOUND: 404,
    WORKSHOP_JOB_CARD_NOT_FOUND: 400,
    WORKSHOP_EMPLOYEE_NOT_FOUND: 400,
    WORKSHOP_JOB_CARD_STATUS_INVALID: 409,
    WORKSHOP_PROCESS_MISMATCH: 400,
    WORKSHOP_ITEM_MISMATCH: 400,
    WORKSHOP_JOB_CARD_ITEM_NOT_FOUND: 400,
    WORKSHOP_JOB_CARD_COMPANY_NOT_FOUND: 400,
    WORKSHOP_INVALID_QTY: 400,
    WORKSHOP_IDEMPOTENCY_CONFLICT: 409,
    WORKSHOP_REVERSAL_EXCEEDS_REGISTERED: 409,
    WORKSHOP_WAGE_RATE_NOT_FOUND: 400,
    WORKSHOP_WAGE_RATE_OVERLAP: 409,
    WORKSHOP_WAGE_RATE_COMPANY_REQUIRED: 422,
    WORKSHOP_WAGE_RATE_SCOPE_REQUIRED: 409,
    WORKSHOP_WAGE_RATE_COMPANY_AMBIGUOUS: 409,
    WORKSHOP_WAGE_RATE_COMPANY_UNRESOLVED: 409,
    WORKSHOP_WAGE_RATE_GLOBAL_FORBIDDEN: 403,
    WORKSHOP_JOB_CARD_SYNC_FAILED: 502,
    WORKSHOP_OUTBOX_NOT_FOUND: 404,
    WORKSHOP_OUTBOX_ALREADY_SUCCEEDED: 409,
    WORKSHOP_OUTBOX_LOCKED: 409,
    WORKSHOP_JOB_CARD_SYNC_PENDING: 202,
    WORKSHOP_INTERNAL_ERROR: 500,
    WORKSHOP_DRY_RUN_DISABLED: 403,
    AUTH_UNAUTHORIZED: 401,
    AUTH_FORBIDDEN: 403,
    PERMISSION_SOURCE_UNAVAILABLE: 503,
    ERPNEXT_SERVICE_UNAVAILABLE: 503,
    ERPNEXT_SERVICE_ACCOUNT_FORBIDDEN: 403,
    ERPNEXT_CUSTOM_FIELD_MISSING: 500,
    ERPNEXT_STOCK_ENTRY_CREATE_FAILED: 502,
    ERPNEXT_STOCK_ENTRY_SUBMIT_FAILED: 502,
    ERPNEXT_STOCK_ENTRY_CANCELLED: 409,
    ERPNEXT_STOCK_ENTRY_STATUS_INVALID: 409,
    ERPNEXT_STOCK_ENTRY_DUPLICATE_EVENT_KEY: 409,
    INTERNAL_API_DISABLED: 403,
    SERVICE_ACCOUNT_RESOURCE_FORBIDDEN: 403,
    SERVICE_ACCOUNT_RESOURCE_SCOPE_REQUIRED: 409,
    AUDIT_WRITE_FAILED: 500,
    DATABASE_WRITE_FAILED: 500,
    DATABASE_READ_FAILED: 500,
    BOM_INTERNAL_ERROR: 500,
}

DEFAULT_MESSAGE_BY_CODE: dict[str, str] = {
    BOM_NOT_FOUND: "BOM 不存在",
    BOM_ITEM_NOT_FOUND: "物料不存在",
    BOM_INVALID_QTY: "数量非法",
    BOM_INVALID_LOSS_RATE: "损耗率非法",
    BOM_OPERATION_RATE_REQUIRED: "工序工价缺失",
    BOM_PUBLISHED_LOCKED: "已发布 BOM 不允许直接修改",
    BOM_DEFAULT_REQUIRES_ACTIVE: "非 active BOM 不能设默认",
    BOM_DEFAULT_CONFLICT: "默认 BOM 冲突，请重试",
    BOM_STATUS_INVALID: "当前状态不允许操作",
    SUBCONTRACT_NOT_FOUND: "外发单不存在",
    SUBCONTRACT_STATUS_INVALID: "外发单当前状态不允许执行该操作",
    SUBCONTRACT_SUPPLIER_INVALID: "加工厂无效",
    SUBCONTRACT_ITEM_NOT_FOUND: "款式/物料不存在",
    SUBCONTRACT_PROCESS_NOT_SUBCONTRACT: "该工序不是外发工序",
    SUBCONTRACT_BOM_ITEM_MISMATCH: "外发单与 BOM 物料不匹配",
    SUBCONTRACT_WAREHOUSE_INVALID: "仓库无效或无仓库权限",
    SUBCONTRACT_INVALID_QTY: "数量非法",
    SUBCONTRACT_RATE_REQUIRED: "外发单价缺失",
    SUBCONTRACT_IDEMPOTENCY_CONFLICT: "幂等键冲突，且请求内容不一致",
    SUBCONTRACT_SETTLEMENT_LOCKED: "外发单已结算锁定",
    SUBCONTRACT_SETTLEMENT_CANDIDATE_NOT_FOUND: "未找到可结算明细",
    SUBCONTRACT_SETTLEMENT_ALREADY_LOCKED: "结算明细已被其他对账单锁定或已结算",
    SUBCONTRACT_SETTLEMENT_STATUS_INVALID: "结算明细状态不允许该操作",
    SUBCONTRACT_SETTLEMENT_IDEMPOTENCY_CONFLICT: "结算幂等键冲突，且请求内容不一致",
    SUBCONTRACT_SETTLEMENT_STATEMENT_REQUIRED: "对账单标识不能为空",
    SUBCONTRACT_STOCK_SYNC_FAILED: "外发库存同步失败",
    SUBCONTRACT_STOCK_OUTBOX_REQUIRED: "库存同步能力未启用，请先完成 Stock Entry outbox",
    SUBCONTRACT_STOCK_OUTBOX_NOT_FOUND: "外发库存同步任务不存在",
    SUBCONTRACT_STOCK_OUTBOX_CONFLICT: "外发库存同步任务状态冲突",
    SUBCONTRACT_STOCK_OUTBOX_ORDER_MISMATCH: "库存同步任务不属于该外发单",
    SUBCONTRACT_STOCK_OUTBOX_ACTION_MISMATCH: "库存同步任务动作与请求不一致",
    SUBCONTRACT_STOCK_OUTBOX_IDEMPOTENCY_MISMATCH: "库存同步任务幂等键与请求不一致",
    SUBCONTRACT_STOCK_OUTBOX_NOT_RETRYABLE: "该库存同步任务状态不允许重试",
    SUBCONTRACT_STOCK_OUTBOX_SCOPE_FORBIDDEN: "无权限重试该库存同步任务",
    SUBCONTRACT_COMPANY_REQUIRED: "外发单 company 不能为空",
    SUBCONTRACT_COMPANY_UNRESOLVED: "无法解析外发单 company",
    SUBCONTRACT_COMPANY_AMBIGUOUS: "外发单 company 存在多个候选，无法唯一确定",
    SUBCONTRACT_SCOPE_BLOCKED: "外发单资源范围已阻断，禁止业务操作",
    SUBCONTRACT_MATERIAL_NOT_IN_BOM: "发料物料不在 BOM 展开范围内",
    SUBCONTRACT_MATERIAL_QTY_EXCEEDED: "发料数量超过剩余可发数量",
    SUBCONTRACT_RECEIPT_WAREHOUSE_REQUIRED: "回料仓不能为空",
    SUBCONTRACT_RECEIPT_BATCH_REQUIRED: "验货必须指定回料批次",
    SUBCONTRACT_RECEIPT_BATCH_NOT_FOUND: "回料批次不存在或不属于当前外发单",
    SUBCONTRACT_RECEIPT_NOT_SYNCED: "回料批次尚未同步成功，禁止验货",
    SUBCONTRACT_RECEIPT_QTY_EXCEEDED: "回料数量超过剩余可回数量",
    SUBCONTRACT_RECEIPT_ITEM_INVALID: "回料 item 非法，必须与外发单 item 一致",
    SUBCONTRACT_INSPECTION_NOT_READY: "当前状态不允许验货",
    SUBCONTRACT_INSPECTION_QTY_EXCEEDED: "验货数量超过批次剩余可验数量",
    SUBCONTRACT_REJECTED_QTY_EXCEEDS_INSPECTED: "不合格数量不能大于验货数量",
    SUBCONTRACT_DEDUCTION_EXCEEDS_GROSS: "扣款金额不能大于验货总金额",
    SUBCONTRACT_MIGRATION_DRY_RUN_ONLY: "当前为 dry-run 预演模式，不允许写入",
    SUBCONTRACT_OUTBOX_REQUIRED: "外发回料能力未启用，请先完成 outbox",
    SUBCONTRACT_INSPECTION_NOT_IMPLEMENTED: "外发验货口径未实现，请先完成 TASK-002F",
    SUBCONTRACT_WAREHOUSE_REQUIRED: "回料仓不能为空",
    SUBCONTRACT_DRY_RUN_DISABLED: "外发内部 dry-run 未启用",
    SUBCONTRACT_WORKER_DISABLED: "外发库存同步内部接口未启用",
    SUBCONTRACT_INTERNAL_ERROR: "外发模块内部错误",
    PRODUCTION_SO_NOT_FOUND: "Sales Order 不存在",
    PRODUCTION_SO_NOT_APPROVED: "Sales Order 未提交",
    PRODUCTION_SO_CLOSED_OR_CANCELLED: "Sales Order 已关闭或已取消",
    PRODUCTION_SO_ITEM_NOT_FOUND: "Sales Order 行不存在",
    PRODUCTION_SO_ITEM_AMBIGUOUS: "Sales Order 存在多行相同 item，必须指定 sales_order_item",
    PRODUCTION_BOM_NOT_FOUND: "BOM 不存在",
    PRODUCTION_BOM_NOT_ACTIVE: "BOM 未生效",
    PRODUCTION_BOM_ITEM_MISMATCH: "BOM 与 Sales Order 行 item 不一致",
    PRODUCTION_PLANNED_QTY_EXCEEDED: "计划数量超过可计划剩余数量",
    PRODUCTION_IDEMPOTENCY_CONFLICT: "幂等键冲突，且请求内容不一致",
    PRODUCTION_WAREHOUSE_REQUIRED: "生产仓库不能为空",
    PRODUCTION_START_DATE_REQUIRED: "开始日期不能为空",
    PRODUCTION_IDEMPOTENCY_KEY_REQUIRED: "幂等键不能为空",
    PRODUCTION_WORK_ORDER_ALREADY_EXISTS: "Work Order 已存在",
    PRODUCTION_WORK_ORDER_SYNC_FAILED: "Work Order 同步失败",
    PRODUCTION_JOB_CARD_SYNC_FAILED: "Job Card 同步失败",
    PRODUCTION_INTERNAL_ERROR: "生产计划模块内部错误",
    STYLE_PROFIT_NOT_FOUND: "利润快照不存在",
    STYLE_PROFIT_CLIENT_SOURCE_FORBIDDEN: "客户端不得提交利润来源明细",
    STYLE_PROFIT_INVALID_PERIOD: "利润快照期间非法",
    STYLE_PROFIT_INVALID_REVENUE_MODE: "revenue_mode 非法",
    STYLE_PROFIT_INVALID_FORMULA_VERSION: "formula_version 非法",
    STYLE_PROFIT_INVALID_IDEMPOTENCY_KEY: "idempotency_key 非法",
    STYLE_PROFIT_SALES_ORDER_REQUIRED: "sales_order 不能为空",
    STYLE_PROFIT_BOM_REQUIRED: "缺少 active/default BOM，无法创建利润快照",
    STYLE_PROFIT_REVENUE_SOURCE_REQUIRED: "未检测到有效收入来源，拒绝创建利润快照",
    STYLE_PROFIT_IDEMPOTENCY_CONFLICT: "幂等键冲突，且请求内容不一致",
    STYLE_PROFIT_SOURCE_UNAVAILABLE: "利润来源服务暂时不可用",
    STYLE_PROFIT_SOURCE_READ_FAILED: "利润来源读取失败",
    STYLE_PROFIT_INTERNAL_ERROR: "利润报表模块内部错误",
    WORKSHOP_TICKET_NOT_FOUND: "工票不存在",
    WORKSHOP_JOB_CARD_NOT_FOUND: "Job Card 不存在",
    WORKSHOP_EMPLOYEE_NOT_FOUND: "员工不存在或无效",
    WORKSHOP_JOB_CARD_STATUS_INVALID: "Job Card 状态不允许登记工票",
    WORKSHOP_PROCESS_MISMATCH: "工票工序与 Job Card 工序不一致",
    WORKSHOP_ITEM_MISMATCH: "请求 item_code 与 Job Card 派生 item_code 不一致",
    WORKSHOP_JOB_CARD_ITEM_NOT_FOUND: "无法从 Job Card / Work Order 派生 item_code",
    WORKSHOP_JOB_CARD_COMPANY_NOT_FOUND: "无法从 Job Card / Work Order 派生 company",
    WORKSHOP_INVALID_QTY: "数量必须大于 0",
    WORKSHOP_IDEMPOTENCY_CONFLICT: "幂等键冲突，且请求内容不一致",
    WORKSHOP_REVERSAL_EXCEEDS_REGISTERED: "撤销数量超过可撤销数量",
    WORKSHOP_WAGE_RATE_NOT_FOUND: "未找到生效工价",
    WORKSHOP_WAGE_RATE_OVERLAP: "工价生效区间重叠",
    WORKSHOP_WAGE_RATE_COMPANY_REQUIRED: "item 工价必须提供 company",
    WORKSHOP_WAGE_RATE_SCOPE_REQUIRED: "历史工价缺少 company 作用域，禁止参与计薪",
    WORKSHOP_WAGE_RATE_COMPANY_AMBIGUOUS: "item_code 对应多个 company，无法自动确定",
    WORKSHOP_WAGE_RATE_COMPANY_UNRESOLVED: "无法解析 item_code 对应 company",
    WORKSHOP_WAGE_RATE_GLOBAL_FORBIDDEN: "无全局权限维护通用工价",
    WORKSHOP_JOB_CARD_SYNC_FAILED: "Job Card 同步失败",
    WORKSHOP_OUTBOX_NOT_FOUND: "同步任务不存在",
    WORKSHOP_OUTBOX_ALREADY_SUCCEEDED: "同步任务已成功，无需重试",
    WORKSHOP_OUTBOX_LOCKED: "同步任务正在处理中，请稍后重试",
    WORKSHOP_JOB_CARD_SYNC_PENDING: "已创建同步任务，等待异步处理",
    WORKSHOP_INTERNAL_ERROR: "车间模块内部错误",
    WORKSHOP_DRY_RUN_DISABLED: "生产环境未开启内部 Worker dry-run",
    AUTH_UNAUTHORIZED: "未登录或登录已过期",
    AUTH_FORBIDDEN: "无权限访问该资源",
    PERMISSION_SOURCE_UNAVAILABLE: "权限来源暂时不可用",
    ERPNEXT_SERVICE_UNAVAILABLE: "ERPNext 服务暂时不可用",
    ERPNEXT_SERVICE_ACCOUNT_FORBIDDEN: "ERPNext 服务账号权限不足",
    ERPNEXT_CUSTOM_FIELD_MISSING: "ERPNext 自定义字段缺失",
    ERPNEXT_STOCK_ENTRY_CREATE_FAILED: "ERPNext Stock Entry 创建失败",
    ERPNEXT_STOCK_ENTRY_SUBMIT_FAILED: "ERPNext Stock Entry 提交失败",
    ERPNEXT_STOCK_ENTRY_CANCELLED: "ERPNext Stock Entry 已取消，禁止视为同步成功",
    ERPNEXT_STOCK_ENTRY_STATUS_INVALID: "ERPNext Stock Entry 状态非法",
    ERPNEXT_STOCK_ENTRY_DUPLICATE_EVENT_KEY: "ERPNext event_key 命中多条单据，禁止继续同步",
    INTERNAL_API_DISABLED: "内部接口未启用",
    SERVICE_ACCOUNT_RESOURCE_FORBIDDEN: "服务账号无资源权限处理该同步任务",
    SERVICE_ACCOUNT_RESOURCE_SCOPE_REQUIRED: "同步任务缺少必要资源范围（company/item_code）",
    AUDIT_WRITE_FAILED: "审计日志写入失败",
    DATABASE_WRITE_FAILED: "数据库写入失败",
    DATABASE_READ_FAILED: "数据库读取失败",
    BOM_INTERNAL_ERROR: "系统内部错误",
}


def status_of(code: str, default: int = 500) -> int:
    return HTTP_STATUS_BY_CODE.get(code, default)


def message_of(code: str, default: str = "请求失败") -> str:
    return DEFAULT_MESSAGE_BY_CODE.get(code, default)
